corrections = {
    'Ec Citityy Of Parañaque':'City of Parañaque',
    'Ornotdalrbiagnu, Erziz (Amlontalban)':'Rodriguez (Montalban)',    
    'Acsi Tcyit Oy,F C Gaveinteeral Trias':'City of General Trias', 
    'Nceabuyao':'Cabuyao',
    'Ncaity Of Calamba':'City of Calamba',
    'Ictyity Of Mandaluyong':'City of Mandaluyong', 
    'Ecsitt Yc Iotyf Muntinlupa':'City of Muntinlupa',
    'Nceitssy Poafrk Muntinlupa':'City of Muntinlupa', 
    ',City Of Mandaluyong':'City of Mandaluyong',
    'Octitey R Od.F, Llaass Ppiiññaas':'City Of Las Piñas',
    'Otbaagl Uciitgy City':'Taguig City',
    'Pcait Cyi Toyf Muntinlupa':'City of Muntinlupa', 
    'Nq,U Neozrothn F Caiitrvyiew':'Quezon City',
    'Bkigaalookan City':'Kalookan City', 
    ',C Caavviittee City':'Cavite City', 
    'Ac Raiiznatla':'Cainta',
    'Ocraog Caiytya,N M Dise Oro City (Capital)':'Cagayan De Oro City (Capital)',
    'Scinitayn Of Urdaneta':'City of Urdaneta', 
    'Nsaan Pedro':'San Pedro', 
    'Liilgiagna Cnit Cyity':'Iligan City',
    'Tdyavao City':'Davao City', 
    'Cdt Davavaaoo Cciittyy':'Davao City', 
    'Llupon':'Lupon',
    'Ictiyt,Y L Oafg Usannata Rosa':'City of Santa Rosa', 
    'Obra, Ccaovoitre':'Bacoor',
    'Acity Of Biñan':'City of Biñan', 
    'Eiligan City':'Iligan City', 
    'Ccitiyty Of Panabo':'City of Panabo',
    'As, Abnutlaac Amnaria':'Santa Maria', 
    'Ggmean,. Cmaavirteiano Alvarez':'Gen. Mariano Alvarez',   
    'Acciatny Of San Jose Del Monte':'City of San Jose Del Monte',
    'Tcy,I Tpya Mofp Asnagna Fernando (Capital)':'City of San Fernando (Capital)',
    'Itmy,A Pbaamlapacnagta City':'Mabalacat City', 
    'Uclaitcya Nof San Jose Del Monte':'City of San Jose Del Monte',
    'Lcaictayn Of San Jose Del Monte':'City of San Jose Del Monte', 
    'Icjaabanatuan City':'Cabanatuan City',
    'Oonelongapo City':'Olongapo City', 
    'Unraga City':'Naga City', 
    'Tlaal Castellana':'La Castellana',
    'Qciutye (Zion Nfr Ocnitty':'Quezon City', 
    'Tyquezon City':'Quezon City',
    'Uqeuzoenzo Cnit Ycity':'Quezon City', 
    'Qityuezon City':'Quezon City', 
    'Icgi Tcyit Yof Pasig':'City of Pasig',
    'Tcyity Of Makati':'City of Makati', 
    'Cpiatryk O2F Muntinlupa':'City of Muntinlupa'
}
correct_sub = {
    'bDaenpED Managed':'DepED Managed', 
    'bSeacntarian':'Sectarian', 
    'bNaonn-Sectarian':'Non-Sectarian',
    'bSUanC Managed':'SUC Managed', 
    'bDaOnST Managed':'DOST Managed',
    'bLUanC':'LUC',
    'bOatnher GA Managed':'Other GA Managed',
    'bLoacnal Government':'Local Government',
    'bLoacnal International School':'Local International School'
}
region_coordinates = {
    'Region I': {'latitude': 16.0833, 'longitude': 120.6000},
    'Region II': {'latitude': 16.9754, 'longitude': 121.8107},
    'Region III': {'latitude': 15.4828, 'longitude': 120.7120},
    'Region IV-A': {'latitude': 14.1000, 'longitude': 121.3000},
    'Region IV-B': {'latitude': 10.5000, 'longitude': 121.0000},
    'Region V': {'latitude': 13.4200, 'longitude': 123.4100},
    'Region VI': {'latitude': 10.7202, 'longitude': 122.5621},
    'Region VII': {'latitude': 10.3157, 'longitude': 123.8854},
    'Region VIII': {'latitude': 11.2500, 'longitude': 125.0000},
    'Region IX': {'latitude': 8.1541, 'longitude': 123.2588},
    'Region X': {'latitude': 8.4811, 'longitude': 124.6459},
    'Region XI': {'latitude': 7.1907, 'longitude': 125.4553},
    'Region XII': {'latitude': 6.2707, 'longitude': 124.6857},
    'CARAGA': {'latitude': 8.8015, 'longitude': 125.7407},
    'BARMM': {'latitude': 6.9568, 'longitude': 124.2422},
    'CAR': {'latitude': 17.3513, 'longitude': 121.1719},
    'NCR': {'latitude': 14.6091, 'longitude': 121.0223}
}
